## 10-2. 복구할 수 있는 상황에는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라 [아이템70] 
- 자바는 문제 상황을 알리는 타입으로 '검사예외', '런타임예외', '에러' (3가지)를 제공함
  - *언제나 100%는 아니지만 참고할 지침
    - 1) 호출하는 쪽에서 복구하리라 여겨지는 상황이라면 검사 예외를 사용하기 
        - ```
          public class FileReaderExample {
             public static void main(String[] args) {
               try {
                     int result = readNumberFromFile("numbers.txt");
                     System.out.println("파일에서 읽은 숫자: " + result);
                  } catch (IOException e) { // 
                     System.err.println("파일 읽기 실패: " + e.getMessage());
                  }
               }

          // 검사 예외를 던질 수 있는 메서드 (여기가 호출하는 쪽 -> 여기서 복구해서 예외가 발생하지 않도록 하는 거면 검사 예외를 사용하라는 듯?)
             public static int readNumberFromFile(String filename) throws IOException {
                 BufferedReader reader = new BufferedReader(new FileReader(filename));
                 try {
                     // 파일에서 한 줄을 읽어와 정수로 변환
                     String line = reader.readLine();
                     return Integer.parseInt(line);
                 } finally {
                     // 리소스 해제
                     reader.close();
                 }
             }
          }
          ```
    - 2) 비검사 throwable은 2가지 > 런타임 예외와 에러임
      - 둘다 동작 측면에서는 다르지 않고, 프로그램에서 잡을 필요가 없거나, 통상적으로 잡지 말아야 함 
      - **프로그램에서 비검사 예외/에러를 던졌다는 것은 복구가 불가능/더 실행해봐야 실이 많다는 뜻**
      - **프로그래밍 오류를 나타낼때는 '런타임 예외'를 사용하기**
        - 대부분의 런타임 예외는 -> 전제조건을 만족하지 못했을 때 발생
        - ex) ArrayIndexOutOfBoundsException -> 배열의 인덱스는 0에서 ~ 배열크기 -1 이여야하는데 이게 안지켜서 난 것

    - [중요] **복구가 가능하다! 라고 믿으면 '검사예외'**, 그렇지 않으면 **런타임 예외**를 사용하자!
    - 3) 에러는 보통 JVM이 자원부족, 불변식 꺠짐 -> 더 이상 수행을 계속할 수 없는 상황에서 사용됨 
      - 즉, 구현하는 비검사 throwable은 모두 RuntimeException의 하위클래스여야 한다는 말
      - Error는 상속하지 말아야하고, throw 문으로 직접 던지는 일도 없어야함!!
        (이때, AssertionError는 예외)
        - ex) throw new OutOfMemoryError("메모리 부족"); // 메모리 부족을 나타내는 에러 -> 메모리부족해서 프로그램이 종료될 수도 있음 
        - ex) AssertionError -> Assert 사용할 때 그 결과가 false이면 나는 에러
- throwable은 이로울게 없으니 절대로 사용하지 말기!
- [결론] 복구가능한 상황 '검사예외'
        프로그래밍 오류는 '비검사 예외'
        확실하지 않으면 '비검사 예외'
        검사예외도 아니고, 런타임 예외도 아닌 throwable은 정의하지도 말기
        '검사예외'인 경우 복구에 필요한 정보를 알려주는 메소드도 제공하기

***
## 10-3. 필요 없는 검사 예외 사용은 피하라 [아이템71]
- 검사예외를 제대로 활용하면 API, 프로그램의 질 높일 수 있음 
  - why? 발생한 문제를 프로그래머가 처리하여 '안전성을 높이게' 해주기 때문
  - [방법] 어떤 메소드가 검사예외 던질 수 있다고 선언됫으면 이를 호출하는 쪽에서 
          'catch'블록을 두어 '예외를 붙잡아 처리하거나', '더 바깜으로 던져 문제 전파' 필요함
  - *검사예외를 던지는 메소드가 스트림 안에서 직접 사용할 수 없음!

- 그럼 어떻게 검사예외/비검사 예외 선택하는지 아는 방법?
  - ```
    } catch (TheCheckedException e) {
        throw new AssertionError(); // 일어날 수 없음 
    }
    
    } catch (TheCheckedException e) {
        e.printStackTrace(); // 음 이것도 별로임
        System.exit(1);
    }
    
    // 위처럼 했는데 더 나은 방법이 없으면 비검사 예외 선택해야함!
    ```

- 검사 예외를 회피하는 가장 쉬운 방법이 있음
  - 1)적절한 결과 타입을 담은 '옵셔널을 반환'하는 것
    - 검사 예외를 던지는 대신 > '단순히 빈 옵셔널' 반환하면 됨
    - [단점] 예외가 발생한 이유를 알려주는 부가 정보를 담을 수 없다는 점
  - 2) 검사 예외를 던지는 메소드를 2개로 쪼개 비검사 예외로 바꿈
    - ```
      // 리팩토링 전 - 검사예외를 던지는 메소드
      try {
         obj.action(args);
      } catch (TheCheckedException e) {
         ... // 예외 상황에 대처
      }
      
      // 리펙토링 후 - 상태검사메소드, 비검사 예외를 던지는 메소드
      if (obj.actionPermitted(args)) {
         obj.action(args); // 먼저 상태를 확인해서 예외를 방지
      } else {
         ... // 예외 상황에 대처
      }
      ```
    - [주의] 위의 경우 외부 동기화 없이 여러 스레드가 동시에 접근할 수 있거나, 외부 요인에 의해 상태가 변할 수 있다면 적절하지 않음 ! 
            why? actionPermitted와 action 호출 사이에 객체의 상태가 변할 수 있기 때문


***
## 10-4. 표준 예외를 사용하라 [아이템72] 
- 표준 예외를 재사용하면 좋음
  - ex) IllegalArgumentException : 호출자가 인수로 부적절한 값을 넘길 떄 던지는 예외
  - ex) IllegalStateException : 대상 객체의 상태가 호출된 메소드를 수행하기에 적합하지 않을 떄 주로 던짐 
        ==> 제대로 초기화되지 않은 객체를 사용하려 할 때 던질 수 있음
  - ex) ConcurrentModificationException : 단일 스레드에서 사용하려고 설계한 객체를 여러 스레드가 동시에 수정하려 할 때 발생
  - ex) UnsupportedOperationException : 클라이언트가 요청한 동작을 대상 객체가 지원하지 않을 때 던짐(흔히 쓰이는 예외는 아님)
        ==> 보통 구현하려는 인터페이스의 메소드 일부를 구현할 수 없을 때 사용됨 -> ex) 원소만 넣을 수 있는 List구현체에 대고 누군가 remove()를 호출하는 때 
      - ```
        public class UnsupportedOperationExample {
            public static void main(String[] args) {
                List<String> readOnlyList = Collections.singletonList("example");

                // UnsupportedOperationException이 발생할 수 있는 상황
                try {
                    readOnlyList.remove(0); // 이 경우, List 구현체가 remove를 지원하지 않으므로 UnsupportedOperationException 발생
                    // 컴파일시에는 런타임 정보를 가지지 않으니까 에러 안뜸
                } catch (UnsupportedOperationException e) {
                    System.err.println("Unsupported operation: " + e.getMessage());
                }
            }
        }
        ```
        
- Exception, RuntimeException, Throwable, Error는 직접 재사용 금지!!!
- 예외는 직렬화할 수 있음 -> 알아두기

***
## 10-5. 추상화 수준에 맞는 예외를 던지라 [아이템73]
- 상위 계층에서 저수준 예외를 잡아 자신의 추상화 수준에 맞는 예외로 바꿔 던져야하는데
  ==> 이를 예외 번역(exception translation)이라고 함
  - ```
    try {
        ... 
    } catch (LowerLevelException e) { // 저수준의 예외가 터지면
        throw new HigherLevelExecption(...); // 고수준의 예외를 던지는 형태
    }
    ```
- 예외 번역시 '저수준 예외가 디버깅에 도움된다면' ==> '예외 연쇄(exception chaning)'을 사용하는 것이 좋음
  - *예외 연쇄 : 문제의 근본 원인인 저수준 예외를 고수준 예외에 실어 보내는 방식 
  - ```
    try {
      ...
    } catch (LowerLevelExcetion cause) {
      // 저수준 예외를 고수준 예외에 실어 보냄
      throw new HigherLevelException(cause); // 이렇게 ㅇㅇ
    }
    ```
  - 대부분의 표준 예외는 '예외 연쇄용 생성자'를 갖추고 있음
  - <-> 그렇지 않은 예외라도 Throwable의 initCause()를 이용해 '원인'을 직접 못박을 수 있음
    - ```
      public class CauseExample {
        public static void main(String[] args) {
          try {
            // 원인이 될 예외를 발생시킴
            throwException();
          } catch (Exception e) {
            // 다른 예외를 발생시키면서 원인 예외를 설정
            AnotherException anotherException = new AnotherException("다른 예외 발생");
            anotherException.initCause(e); // 여서 예외 원인 직접 못박음

            // 두 번째 예외를 처리
            handleException(anotherException);
          }
      }

      public static void throwException() throws Exception {
        throw new Exception("원인 예외 발생");
      }

      public static void handleException(AnotherException e) {
        // 두 번째 예외를 처리
        System.err.println("두 번째 예외 처리: " + e.getMessage());
        // 원인 예외에 접근
        Throwable cause = e.getCause();
        if (cause != null) {
          System.err.println("원인 예외: " + cause.getMessage());
        }
      }

      // 새로운 예외 클래스 정의
      public static class AnotherException extends Exception {
          public AnotherException(String message) {
            super(message);
          }
        }
      }
      
      // 근데 이 방법 남용하진 말기! 
      ```
- 아래 계층에서 예외를 피할 수 없으면, 상위 계층에서 그 예외를 조용히 처리하여 문제를 API 호출자에게 전파하지 않는 방법도 있음
  - [참고] 위의 경우 발생한 예외는 java.util.logging 과 같은 적절한 로깅 기능을 활용해 기록해두기

***

## 10-6. 메소드가 던지는 모든 예외를 문서화하라 [아이템74]
- 자바독의 @throws 태그를 사용하여 정확히 문서화하는 것은 중요 -> 메소드가 던지는 예외는 그 메소드를 올바로이 사용하는데 중요한 단서기 때문
- 공통 상위 클래스 하나로 뭉뚱그려 선언하지 말기
    - ex) 메소드가 Exception이나 Throwable을 던진다고 선언하면 안됨s
    - [예외] main 메소드
        - main은 오직 JVM만이 호출하므로 Exception을 던지도록 선언해도 괜찮음
- 비검사 예외도 검사 예외처럼 문서화해두면 좋음
    - *비검사 예외(unCheckedException) : 일반적으로 프로그래밍 오류를 뜻함 ex) nullpointexception
    - 잘 정비된 비검사 예외 문서는 -> 그 메소드를 성공적으로 수행하기 위한 전제조건이 됨
    - 비검사 예외는 메소드 선언의 throws 목록에 넣지 말기 -> 검사 예외랑 구분해주는게 좋음!
    - 현실적으로 비검사 예외를 문서화하기 불가능할때가 있음 -> 클래스 수정하면서 새로운 비검사 예외를 던지게 되도 소스 호환성과 바이너리 호환성이 그대로 유지된다는게 큰 이유
      - ```
        // 기존의 클래스
        public class ExampleClass {
          public void someMethod() {
          // 기존의 코드
          }
        }
      
        // 클래스를 수정하여 새로운 RuntimeException을 던지는 경우:
        // 수정된 클래스
        public class ExampleClass {
            public void someMethod() {
                // 수정된 코드
                throw new CustomRuntimeException("This is a new unchecked exception.");
            }
        }
        // 여기서 CustomRuntimeException은 RuntimeException의 하위 클래스로, 새로운 비검사 예외를 나타냅니다.
        이러한 변경이 소스 호환성과 바이너리 호환성에 유리한 이유는 다음과 같습니다:
        소스 호환성(Source Compatibility): 다른 코드에서 이 클래스를 사용하는 경우, 새로운 예외를 던진다고 해도 컴파일 에러가 발생하지 않습니다. 즉, 코드를 수정하지 않아도 기존 소스 코드와 호환성을 유지할 수 있습니다.
        바이너리 호환성(Binary Compatibility): 클래스의 바이트 코드가 변경되더라도, 기존에 컴파일된 코드가 정상적으로 동작합니다. 따라서, 새로운 예외를 던지더라도 기존의 바이너리 코드와의 호환성이 유지됩니다.
        ```
- 한 클래스에 정의된 많은 메소드가 같은 이유로 예외던지는 경우
    - => 각각 메소드말고 클래스 설명에 추가해도 됨
    - ex) NullPointerException이 가장 흔한 사례

- [결론] 메소드가 던질 가능성 있는 모든 예외 문서화
  문서화에는 자바독의 @throws 태그 사용
  검사 예외만 메소드 선언의 throws문에 일일이 선언
  비검사 예외는 메소드 선언에는 기입하지 말기
  why? 뭐가 검사예외고 비검사예외인지 사람들이 헷갈림

***
## 10-7. 예외의 상세 메시지에 실패 관련 정보를 담으라 [아이템75]
- 자바 시스템은 예외로 프로그램이 실패하면 그 예외의 스택 추적(stack trace)정보를 자동으로 출력함
    - 스택 추적 : 예외의 toString 메소드를 호출해 얻는 문자열
- 실패 순간을 포착하려면 발생한 예외에 관여된 모든 매개변수/필드의 값을 실패 메시지에 담아야 함
    - ex) IndexOutOfBoundsException의 경우는 당시 범위의 최솟값/최댓값, 범위를 벗어났다는 인덱스의 값을 담아야 함!
- 근데 장황할 필욘 없음, 필요한 정보만 담아서 상세하게 기록해두는 것이 가장 좋음

- [주의] 예외의 상세 메시지와 최종 사용자에게 보여줄 오류 메시지는 혼동하지 말기
    - 최종 사용자에게는 : 친절한 안내 메시지 보여주기
    - 예외 메시지는 : 가독성 보다 < 담긴 내용이 훨씬 중요

- 자바9에서 IndexOutOfBoundsException 에 '정수 인덱스 값'을 받는 생성자가 추가됨! 알아두
